### ISSUE TITLE
npm package issue

### ISSUE THREAD

**Issue by svantreeck** [UTGuy/mikro-orm-mssql#2]
Hello, I am trying to set up an application with this driver and am getting an issue trying to load the npm package (1.0.2)--it seems like the entry point in the package.json is listed as `index.js`, but the package contents are `index.ts`.  If I manually set it to use `index.ts`, I get errors saying `Unexpected token export` at `export * from './driver';` in the index.ts.  Would it be possible to compile this as a javascript package for usage from npm instead of leaving in typescript?  

Original Error:
```shell
Error: Cannot find module '<path>/node_modules/mikro-orm-mssql/index.js'. Please verify that the package.json has a valid "main" entry
```

**Comment by UTGuy** [comment]
I've updated the entrypoint to `index.ts` ... this library is meant to be used with mikro-orm v4 (which uses typescript). Try 1.0.3
I should also caveat this library that it's a stopgap until the owner of Mikro-orm finishes the mssql driver he is working on. I've been in collaboration with him for some time now on this.

**Comment by svantreeck** [comment]
Thanks!

**Comment by UTGuy** [comment]
@svantreeck I've update this to v1.0.7 today
